# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: 'SPDX License Header Verification'
description: 'Verify that files contain the required SPDX license headers'

inputs:
  directory:
    description: 'Directory to scan for files'
    required: false
    default: '.'
  license:
    description: 'SPDX license identifier to verify (e.g., Apache-2.0, MIT, GPL-3.0)'
    required: false
    default: 'Apache-2.0'
  skip:
    description: 'Comma-separated list of patterns to skip'
    required: false
    default: ''
  debug:
    description: 'Enable debug output'
    required: false
    default: 'false'
  enable_default_file_type:
    description: 'Enable default file type handling for files without extensions'
    required: false
    default: ''
  disable_default_file_type:
    description: 'Disable default file type handling for files without extensions'
    required: false
    default: 'false'
  default_file_type:
    description: 'Override default file type language (e.g., text, python)'
    required: false
    default: ''
  pre_commit_mode:
    description: 'Only check files tracked by Git (for pre-commit hooks)'
    required: false
    default: 'false'
  reuse_compliance:
    description: 'Check REUSE compliance (validates license and copyright headers)'
    required: false
    default: 'false'

outputs:
  success:
    description: 'Whether all files have correct license headers'
  missing-files:
    description: 'Number of files missing correct license headers'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      # yamllint disable-line rule:line-length
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version-file: 'pyproject.toml'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        cd ${{ github.action_path }}
        # pdm install --prod --no-editable
        pdm install

    - name: Run SPDX verification
      shell: bash
      run: |
        cd ${{ github.action_path }}
        pdm run python spdx_verify.py
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_LICENSE: ${{ inputs.license }}
        INPUT_SKIP: ${{ inputs.skip }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_ENABLE_DEFAULT_FILE_TYPE: ${{ inputs.enable_default_file_type }}
        INPUT_DISABLE_DEFAULT_FILE_TYPE: ${{ inputs.disable_default_file_type }}
        INPUT_DEFAULT_FILE_TYPE: ${{ inputs.default_file_type }}
        INPUT_PRE_COMMIT_MODE: ${{ inputs.pre_commit_mode }}
        INPUT_REUSE_COMPLIANCE: ${{ inputs.reuse_compliance }}
