version = 1

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Licensing statement required for GHA tests and linting to pass for only this repository

[[annotations]]
path = [
	 "README.md",
	 "tests/**",
	 "PROJECT_SUMMARY.md",
	 "tests/test_files/**",
	 "*.lock",
     "test_coverage_report*"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
