---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: Demo SPDX Check

on:
  workflow_dispatch:  # Manual trigger for demo

jobs:
  spdx-demo:
    runs-on: ubuntu-latest
    name: SPDX License Header Demo

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run SPDX verification
        id: spdx-check
        uses: ./
        with:
          directory: '.'
          license: 'Apache-2.0'
          skip: 'tests/test_files/**,*.md,LICENSE,requirements.txt'
          debug: 'true'

      - name: Show results
        if: always()
        run: |
          echo "SPDX Check Success: ${{ steps.spdx-check.outputs.success }}"
          echo "Missing Files Count: ${{ steps.spdx-check.outputs.missing-files }}"

          if [ "${{ steps.spdx-check.outputs.success }}" == "true" ]; then
            echo "✅ All files have correct SPDX license headers!"
          else
            echo "❌ Some files are missing correct license headers"
            echo "Please add the required SPDX-License-Identifier headers"
          fi
